# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.

env:
  ENV_VAR_LOCAL: ${{ vars.ENV_VAR }}

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: dev
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: |
        echo "Env var ${{ vars.ENV_VAR }}"
        echo "Env secrets syntax error ${{ secrets.ENV_SECROT }}"
        echo "Env secrets ${{ secrets.ENV_SECRET }}"
